{{- if (eq "sdwebui" .Values.runtime.type) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sdchart.fullname" . }}-webui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdchart.labels" . | nindent 4 }}
    {{- if .Values.runtime.labels }}
    {{- toYaml .Values.runtime.labels | nindent 4 }}
    {{- end }}
    app: webui
    runtime-type: sdwebui
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: inference-api
    {{- include "sdchart.selectorLabels" . | nindent 4 }}
{{- end }}